keys:
  G7:
    down: amixer set Master 5%-
    held: amixer set Master 5%-
  G8:
    down: amixer set Master 5%+
    held: amixer set Master 5%+
  G9:
    down: ydotool key alt+Left
  G10:
    down: ydotool click --repeat 2 1
  G11:
    down: swaymsg "workspace next"
  G12:
    down: wofi
  G13:
    down: ydotool click left
  G14:
    down: swaymsg "workspace prev"
  G15:
    down: ydotool key ctrl+c
  G16:
    down: ydotool key ctrl+v
  G17:
    down: ydotool key ctrl+x
device: /dev/input/by-id/usb-Logitech_Gaming_Mouse_G600_1836A07F43730017-if01-event-kbd
